name: Automated tests

on:
  push:
     
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # in case a browser hangs
    steps:
      - 
        name: Login to GitHub Container Registry
        uses: actions/checkout@v3
      
      - uses: maxmilton/action-setup-playwright@v1
        with:
          browsers: chromium, firefox, webkit # optional
          headless: true # optional

      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run test-e2e
